version: "3.9"

services:
  db:
    image: mariadb:latest
    container_name: lemp_mariadb
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    restart: always
    # restart: unless-stopped
    networks:
      - web_network
  php:
    depends_on:
      - db
    build: php/
    container_name: lemp_php
    volumes:
      - ./public_html/:/var/www/html
    expose:
      - "9000"
    restart: always
    networks:
      - web_network
  nginx:
    image: nginx:stable-alpine
    container_name: lemp_nginx
    volumes:
      - ./public_html/:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "88:80"
    restart: always
    networks:
      - web_network

networks:
  web_network:
    name: lemp
    driver: bridge    